#version: "3"
#services:
#    springapp:
#      build: .
#      container_name: springapp
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
#      ports:
#        - 8000:8080
#      restart: always
#      depends_on:
#        - db
#    db:
#      image: postgres
#      container_name: db
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=123
#        - POSTGRES_DB=test
#        - PGDATA=/var/lib/postgresql/data/pgdata
#      ports:
#        - 5000:5432
#      volumes:
#        - pgdata:/var/lib/postgresql/data
#      restart: always
#    pgadmin:
#      container_name: pgadmin4_container
#      image: dpage/pgadmin4
#      restart: always
#
#      environment:
#        - PGADMIN_DEFAULT_EMAIL=test@gmail.com
#        - PGADMIN_DEFAULT_PASSWORD=123456
#        - PGADMIN_LISTEN_PORT= 80
#      volumes:
#        - pgadmin-data:/var/lib/pgadmin
#
#      ports:
#        - "5050:80"
#volumes:
#    pgdata:
#    pgadmin-data:
